sentiment:
  toolTipText: 'This column shows the tone of the comment.'
  apiCall: 'https://peerlogic.csc.ncsu.edu/sentiment/analyze_reviews_bulk'
  selected: true
problem:
  toolTipText: 'This shows whether any problem is mentioned in the comment or not.'
  apiCall: 'http://152.7.99.200:5000/problem'
  selected: true
suggestion:
  toolTipText: 'This shows whether any problem is mentioned in the comment or not.'
  apiCall: 'http://152.7.99.200:5000/suggestions'
  selected: true